//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outstanding
    {
        public int O_ID { get; set; }
        public System.DateTime O_month { get; set; }
        public string O_pID { get; set; }
        public double O_fees { get; set; }
        public string O_remark { get; set; }
        public int O_status { get; set; }
    }
}
