//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public string parents_ic { get; set; }
        public string parents_name { get; set; }
        public string parents_pass { get; set; }
        public string parents_email { get; set; }
        public string parents_phone { get; set; }
        public string parents_address { get; set; }
    }
}
