//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int confirmation_id { get; set; }
        public string student_ic { get; set; }
        public string parent_ic { get; set; }
        public double payment_fee { get; set; }
        public string ref_num { get; set; }
        public int status_id { get; set; }
        public System.DateTime confirmation_date { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_detail { get; set; }
        public string payment_feedetails { get; set; }
        public string filename { get; set; }

        public int meal_fee { get; set; }

        public int transport_fee { get; set; }

        public int first_register { get; set; }

        public float lower_discount { get; set; }
    }
}
