//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studRegister
    {
        public string studreg_ic { get; set; }
        public string subject_1 { get; set; }
        public string subject_2 { get; set; }
        public string subject_3 { get; set; }
        public string subject_4 { get; set; }
        public string subject_5 { get; set; }
        public string subject_6 { get; set; }
        public string subject_7 { get; set; }
    }
}
