//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string student_ic { get; set; }
        public string student_name { get; set; }
        public string student_cname { get; set; }
        public int student_package { get; set; }
        public System.DateTime student_dob { get; set; }
        public string student_gender { get; set; }
        public string student_category { get; set; }
        public string student_year { get; set; }
        public string parent_ic { get; set; }
    }
}
