//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_type { get; set; }
        public string subject_year { get; set; }
    }
}
